site_name: barangay
site_description: Python Package for Philippine Standard Geographic Code
site_author: bendlikeabamboo
repo_url: https://github.com/bendlikeabamboo/barangay
site_url: https://bendlikeabamboo.github.io/barangay/

theme:
  name: shadcn
  favicon: favicon.png
  extra_css:
    - stylesheets/extra.css

nav:
  - barangay: index.md
  - API Reference: api.md
  - CLI Reference: cli.md
  - Configuration: configuration.md
  - Data Model Reference:
    - Overview: data_models/overview.md
    - Python: data_models/python.md
  - Contributing:
    - Overview: contributing/index.md
    - Data Update: contributing/data_update.md


markdown_extensions:
  - admonition
  - codehilite
  - tables

plugins:
  - search
  - badges