from __future__ import annotations

from typing import TYPE_CHECKING, Any, Iterator

from barangay.models import (
    AdminDivRecord,
    AdminLevel,
    PluginExtension,
    PluginExtensionMetadata,
    PluginInfo,
    SearchResult,
)
from barangay.types import MatchHook  # noqa: F401

if TYPE_CHECKING:
    import pandas as pd

class MultipleResultsError(Exception): ...
class RecordNotFoundError(LookupError): ...

class PluginAccessor:
    __slots__ = ("_data", "_metadata")

    def __init__(
        self,
        data: dict[str, Any] | list[dict[str, Any]],
        metadata: PluginExtensionMetadata,
    ) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def to_dict(self) -> dict[str, Any] | list[dict[str, Any]]: ...
    @property
    def metadata(self) -> PluginExtensionMetadata: ...
    @property
    def is_array(self) -> bool: ...
    @property
    def rows(self) -> list[dict]: ...

class HierarchyIndex:
    def __init__(self, records: list[AdminDivRecord]) -> None: ...
    def get(self, psgc_id: str) -> AdminDivRecord | None: ...
    def parent(self, record: AdminDivRecord) -> AdminDivRecord | None: ...
    def children(self, psgc_id: str) -> list[AdminDivRecord]: ...
    def ancestors(self, record: AdminDivRecord) -> list[AdminDivRecord]: ...
    def resolve_region(self, record: AdminDivRecord) -> AdminDivRecord | None: ...
    def resolve_province(self, record: AdminDivRecord) -> AdminDivRecord | None: ...
    def resolve_municipality(self, record: AdminDivRecord) -> AdminDivRecord | None: ...
    def resolve_city(self, record: AdminDivRecord) -> AdminDivRecord | None: ...
    def records_of_type(self, level: AdminLevel) -> list[AdminDivRecord]: ...

class EnrichedRecord:
    __slots__ = ("_record", "_index")

    def __init__(self, record: AdminDivRecord, index: HierarchyIndex) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def to_dict(self) -> dict: ...
    @property
    def name(self) -> str: ...
    @property
    def psgc_id(self) -> str: ...
    @property
    def type(self) -> AdminLevel: ...
    @property
    def parent_psgc_id(self) -> str: ...
    @property
    def nicknames(self) -> list[str] | None: ...
    @property
    def extensions(self) -> list[PluginExtension]: ...
    @property
    def region(self) -> str | None: ...
    @property
    def province(self) -> str | None: ...
    @property
    def municipality(self) -> str | None: ...
    @property
    def city(self) -> str | None: ...
    @property
    def parent(self) -> EnrichedRecord | None: ...
    @property
    def children(self) -> list[EnrichedRecord]: ...
    @property
    def ancestors(self) -> list[EnrichedRecord]: ...

class DatabaseView:
    def get(
        self, *, psgc_id: str | None = None, name: str | None = None
    ) -> EnrichedRecord: ...
    def lookup(self, psgc_id: str) -> EnrichedRecord | None: ...
    def search_fuzzy(
        self,
        query: str,
        *,
        match_hooks: list[Any] | None = None,
        threshold: float = 60.0,
        limit: int = 5,
        as_of: str | None = None,
    ) -> list[SearchResult]: ...
    def __iter__(self) -> Iterator[EnrichedRecord]: ...
    def __len__(self) -> int: ...
    def __contains__(self, psgc_id: str) -> bool: ...
    def __repr__(self) -> str: ...
    def to_dicts(self) -> list[dict]: ...
    def to_frame(self) -> pd.DataFrame: ...

class _VersionState:
    as_of: str | None
    def set(self, as_of: str | None) -> None: ...

class Database:
    _version_state: _VersionState
    def _view(self, level: AdminLevel | None) -> DatabaseView: ...
    @property
    def regions(self) -> DatabaseView: ...
    @property
    def provinces(self) -> DatabaseView: ...
    @property
    def municipalities(self) -> DatabaseView: ...
    @property
    def cities(self) -> DatabaseView: ...
    @property
    def submunicipalities(self) -> DatabaseView: ...
    @property
    def barangays(self) -> DatabaseView: ...
    @property
    def special_geographic_areas(self) -> DatabaseView: ...
    @property
    def all_records(self) -> DatabaseView: ...
    def invalidate_cache(self) -> None: ...
    def use_plugins(
        self,
        plugins: list[str] | None = None,
        levels: list[AdminLevel] | None = None,
        loader: Any = None,
    ) -> None: ...
    def available_plugins(self) -> list[PluginInfo]: ...
    def active_plugins(self) -> list[str]: ...
