# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath(".."))


# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "barangay"
copyright = "2026, bendlikeabamboo"
author = "bendlikeabamboo"
version = "2026.1.13.1"
release = "2026.1.13.1"


# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",  # Automatic documentation from docstrings
    "sphinx.ext.napoleon",  # Support for NumPy and Google style docstrings
    "sphinx.ext.viewcode",  # Add links to highlighted source code
    "sphinx.ext.intersphinx",  # Link to other project's documentation
    "sphinx.ext.todo",  # Support for todo items
    "sphinx.ext.coverage",  # Collect doc coverage stats
    "sphinx.ext.ifconfig",  # Include content based on configuration
    "sphinx.ext.githubpages",  # Create .nojekyll file for GitHub Pages
    "sphinx.ext.autosectionlabel",  # Allow reference sections by their title
    "sphinx.ext.autosummary",  # Generate autodoc summaries
    "sphinx.ext.doctest",  # Test snippets in the documentation
    "sphinx_copybutton",  # Add copy button to code blocks
    "sphinx_design",  # Additional design components
    "sphinx.ext.autodoc.typehints",  # Type hints support
]

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Autodoc settings
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
}
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"
autodoc_mock_imports = []

# Intersphinx mapping
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "pydantic": ("https://docs.pydantic.dev/", None),
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The suffix(es) of source filenames.
source_suffix = {
    ".rst": "restructuredtext",
}

# The master document
master_doc = "index"

# The language for content autogenerated by Sphinx.
language = "en"

# Pygments (syntax highlighting) style
pygments_style = "sphinx"

# Keep warnings
keep_warnings = True

# Numbered figures
numfig = True

# Todo extension
todo_include_todos = True


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# The theme to use for HTML and HTML Help pages.
html_theme = "shibuya"

# Theme options
html_theme_options = {
    # "sidebar_hide_name": False,
    # "show_nav_level": 2,
    # "navigation_with_keys": True,
    # "light_css_variables": {
    #     "color-brand-primary": "#0066cc",
    #     "color-brand-content": "#0066cc",
    # },
    # "dark_css_variables": {
    #     "color-brand-primary": "#3399ff",
    #     "color-brand-content": "#3399ff",
    # },
    # "show_prev_next": True,
    # "show_nav_level": 5,
    # "navigation_depth": 5,
    # "collapse_navigation": True,
    # "sticky_navigation": True,
    # "includehidden": True,
    # "titles_only": False,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom CSS files
html_css_files = ["custom.css"]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = '_static/logo.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.
# html_favicon = '_static/favicon.ico'


# -- Options for HTMLHelp output ---------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-htmlhelp-output

# Output file base name for HTML help builder.
htmlhelp_basename = "barangaydoc"


# -- Options for LaTeX output ------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-latex-output

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "barangay.tex", "barangay Documentation", "bendlikeabamboo", "manual"),
]


# -- Options for manual page output ------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-manual-page-output

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "barangay", "barangay Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-texinfo-output

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "barangay",
        "barangay Documentation",
        author,
        "barangay",
        "Philippine geographic/administrative data with fuzzy search.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text.
epub_identifier = "https://github.com/bendlikeabamboo/barangay"

# A unique identification for the text.
epub_uid = project

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]
